lib/listless_web/router.ex
defmodule ListlessWeb.Router do
  use ListlessWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ListlessWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    scope "/login" do
      get "/", LoginController, :index
      post "/login", LoginController, :login
      post "/logout", LoginController, :logout
    end

    scope "/user" do
      get "/:user_id", UserController, :index
      post "/create", UserController, :create
    end

    scope "/list" do
      get "/:list_id", ListController, :index
      post "/create", ListController, :create
    end

    scope "/item" do
      post "/create", ItemController, :create
      post "/delete/:id", ItemController, :delete
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", ListlessWeb do
  #   pipe_through :api
  # end
end

lib/listless/user.ex
defmodule Listless.User do
  use Ecto.Schema
  import Ecto.Changeset
  alias Comeonin.Bcrypt

  @primary_key {:id, :binary_id, autogenerate: true}
  @derive {Phoenix.Param, key: :id}

  schema "users" do
    field :email, :string
    field :password, :string
    field :name, :string

    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:email, :password, :name])
    |> validate_required([:email, :password, :name])
    |> unique_constraint(:email)
    |> hash_password()
  end

  def hash_password(%Ecto.Changeset{valid?: true, changes: %{password: password}} = changeset) do
    change(changeset, password: Bcrypt.hashpwsalt(password))
  end
end

lib/listless_web/controllers/user_controller.ex
defmodule ListlessWeb.UserController do
  use ListlessWeb, :controller
  alias Listless.User
  alias Listless.Repo

  def index(conn, %{"user_id" => user_id}) do
    render(conn, "index.html", user_id: user_id)
  end

  def create(conn, params) do
    %User{}
    |> User.changeset(params)
    |> Repo.insert()
    |> case do
      {:ok, _user} ->
        put_flash(conn, :info, "Account created successfully. Welcome to Listless!")
        case Listless.Auth.login(params) do
          {:ok, _user} ->
            conn
            |> put_session(:current_user, params.email)
            |> redirect(to: "/")
          {:error, _error} ->
            conn
            |> put_flash(:error, "Something went horribly wrong. This should never happen. Please contact a developer ASAP.")
            |> redirect(to: "/login")
        end
      {:error, _errors} ->
        conn
        |> put_flash(:error, "Something went wrong. Please try again.")
        |> redirect(to: login_path(conn, :index))
    end
  end
end

lib/listless_web/views/user_view.ex
defmodule ListlessWeb.UserView do
  use ListlessWeb, :view
  import Ecto.Query, only: [from: 2]
  alias Listless.Repo
  alias Listless.List

  def created_lists(user_id) do
    from(l in List, where: l.user_id == ^user_id)
    |> Repo.all()
  end
end

lib/listless_web/templates/user/index.html.eex
<%= render ListlessWeb.PageView, "header.html", conn: @conn %>
<article>
  <div style="text-align: center;">
    <h2>Lists</h2>
    <%= for list <- created_lists(Listless.Util.convert_to_uuid(@user_id)) do %>
      <a class="btn btn-default" href="<%= "/list/" <> Listless.Util.convert_to_base64(list.id) %>"><%= list.title %></a>
    <% end %>
    <%= if Listless.Util.convert_to_uuid(@user_id) == Listless.Auth.current_user(@conn).id do %>
      <%= form_for @conn, list_path(@conn, :create), [style: "width: 20%; margin-left: 40%;"], fn f -> %>
        <div class="input-field">
          <%= text_input f, :title, [id: "title", required: true] %>
          <label for="title">Title</label>
        </div>
        <p>
          <label>
            <%= radio_button f, :is_public, true, [checked: true] %>
            <span>Public</span>
          </label>
        </p>
        <p>
          <label>
            <%= radio_button f, :is_public, false %>
            <span>Private</span>
          </label>
        </p>
        <%= hidden_input f, :user_id, [value: Listless.Util.convert_to_uuid(@user_id)] %>
        <%= submit "New List", [class: "btn white"] %>
      <% end %>
      <%= form_for @conn, login_path(@conn, :logout), fn f -> %>
        <%= submit "Logout", [class: "btn red"] %>
      <% end %>
    <% end %>
  </div>
</article>