lib/listless_web/router.ex
defmodule ListlessWeb.Router do
  use ListlessWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ListlessWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    scope "/login" do
      get "/", LoginController, :index
      post "/login", LoginController, :login
      post "/logout", LoginController, :logout
    end

    scope "/user" do
      get "/:user_id", UserController, :index
      post "/create", UserController, :create
    end

    scope "/list" do
      get "/:list_id", ListController, :index
      post "/create", ListController, :create
    end

    scope "/item" do
      post "/create", ItemController, :create
      post "/delete/:id", ItemController, :delete
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", ListlessWeb do
  #   pipe_through :api
  # end
end

lib/listless_web/controllers/login_controller.ex
defmodule ListlessWeb.LoginController do
  use ListlessWeb, :controller
  alias Listless.Auth

  def index(conn, _params) do
    render conn, "index.html"
  end

  def login(conn, params) do
    case Auth.login(params) do
      {:ok, user} ->
        conn
        |> put_session(:current_user, user.email)
        |> redirect(to: "/")
      {:error, _error} ->
        conn
        |> put_flash(:error, "Invalid email or password. Please try again.")
        |> redirect(to: "/login")
    end
  end

  def logout(conn, params) do
    conn
    |> delete_session(:current_user)
    |> redirect(to: "/")
  end
end

lib/listless_web/views/login_view.ex
defmodule ListlessWeb.LoginView do
  use ListlessWeb, :view
end

lib/listless_web/templates/login/index.html.eex
<%
  info = get_flash(@conn, :info)
  error = get_flash(@conn, :error)
%>
<%= if info do %>
  <div class="alert alert-info" style="position: fixed; width: 100%;" role="alert"><%= info %></div>
<% end %>
<%= if error do %>
  <div class="alert alert-info" style="position: fixed; width: 100%;" role="alert"><%= error %></div>
<% end %>
<img class="login-logo" src="<%= static_path(@conn, "/images/logo.svg") %>" />
<div class="vertical-divider"></div>
<div class="row" style="width: 100%;">
  <div class="col s3"></div> <!-- Spacer -->
  <div class="col s2" style="padding-top: 310px">
    <%= form_for @conn, login_path(@conn, :login), [style: "text-align: center;"], fn f -> %>
      <h3 class="h3 mb-3 font-weight-normal">Log in</h3>
      <div class="input-field">
        <%= email_input f, :email, [id: "login-email", required: true] %>
        <label for="login-email">Email Address</label>
      </div>
      <div class="input-field">
        <%= password_input f, :password, [id: "login-pwd", required: true] %>
        <label for="login-pwd">Password</label>
      </div>
      <%= submit "Log in", [class: "btn white"] %>
    <% end %>
  </div>
  <div class="col s2" style="text-align: center;"></div> <!-- Spacer -->
  <div class="col s2" style="padding-top: 250px">
    <%= form_for @conn, user_path(@conn, :create), [style: "text-align: center;"], fn f -> %>
      <h3 class="h3 mb-3 font-weight-normal">Sign up</h3>
      <div class="input-field">
        <%= email_input f, :email, [id: "signup-email", required: true] %>
        <label for="signup-email">Email Address</label>
      </div>
      <div class="input-field">
        <%= text_input f, :name, [id: "signup-name", required: true] %>
        <label for="signup-name">Display Name</label>
      </div>
      <div class="input-field">
        <%= password_input f, :password, [id: "signup-pwd", required: true] %>
        <label for="signup-pwd">Password</label>
      </div>
      <div class="input-field">
        <%= password_input f, :confirm_password, [id: "signup-pwd-confirm", required: true] %>
        <label for="signup-pwd-confirm">Confirm Password</label>
      </div>
      <%= submit "Sign up", [class: "btn white"] %>
    <% end %>
  </div>
</div>