lib/listless_web/router.ex
defmodule ListlessWeb.Router do
  use ListlessWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ListlessWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    scope "/login" do
      get "/", LoginController, :index
      post "/login", LoginController, :login
      post "/logout", LoginController, :logout
    end

    scope "/user" do
      get "/:user_id", UserController, :index
      post "/create", UserController, :create
    end

    scope "/list" do
      get "/:list_id", ListController, :index
      post "/create", ListController, :create
    end

    scope "/item" do
      post "/create", ItemController, :create
      post "/delete/:id", ItemController, :delete
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", ListlessWeb do
  #   pipe_through :api
  # end
end

lib/listless/list.ex
defmodule Listless.List do
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @derive {Phoenix.Param, key: :id}

  schema "lists" do
    field :is_public, :boolean, default: false
    field :user_id, Ecto.UUID
    field :title, :string

    timestamps()
  end

  @doc false
  def changeset(list, attrs) do
    list
    |> cast(attrs, [:is_public, :user_id, :title])
    |> validate_required([:is_public, :user_id, :title])
  end
end

lib/listless_web/controllers/list_controller.ex
defmodule ListlessWeb.ListController do
  use ListlessWeb, :controller
  alias Listless.Repo
  alias Listless.List

  def index(conn, %{"list_id" => list_id}) do
    render(conn, "index.html", list_id: list_id)
  end

  def create(conn, params) do
    %List{}
    |> List.changeset(params)
    |> Repo.insert()
    |> case do
      {:ok, list} ->
        conn
        |> put_flash(:info, "List created successfully!")
        |> redirect(to: ("/list/" <> to_string(list.id)))
      {:error, _error} ->
        conn
        |> put_flash(:error, "Failed to create list. Please try again.")
        |> redirect(to: "/user/" <> to_string(params["user_id"]))
    end
  end
end

lib/listless_web/views/list_view.ex
defmodule ListlessWeb.ListView do
  use ListlessWeb, :view
  import Ecto.Query, only: [from: 2]
  alias Listless.Repo
  alias Listless.List
  alias Listless.Item

  def get_list(list_id) do
    Repo.get(List, list_id)
  end

  def list_items(list_id) do
    from(i in Item, where: i.list_id == ^list_id)
    |> Repo.all()
  end
end

lib/listless_web/templates/list/index.html.eex
<% list = get_list(Listless.Util.convert_to_uuid(@list_id)) %>

<%= render ListlessWeb.PageView, "header.html", conn: @conn %>
<article style="text-align: center;">
  <h2><%= list.title %></h2>
  <%= for item <- list_items(Listless.Util.convert_to_uuid(@list_id)) do %>
    <a class="btn white item" href="<%= item.link %>">
      <img src="<%= item.image %>" style="width: 10px; height: 10px;">
      <%= item.title %>
      <span><%= item.price %></span>
      <%= button to: "/item/delete/" <> to_string(item.id), class: "btn white" do %>
        <i class="material-icons large">delete</i>
      <% end %>
    </a>
  <% end %>
  <%= if Listless.Auth.current_user(@conn) != nil and list.user_id == Listless.Auth.current_user(@conn).id do %>
    <div style="width: 40%; left: 30%; position: absolute">
      <%= form_for @conn, item_path(@conn, :create), [], fn f -> %>
        <div class="input-field">
          <%= text_input f, :title, [id: "title", required: true] %>
          <label for="title">Title</label>
        </div>
        <div class="input-field">
          <%= text_input f, :link, [id: "link", required: true] %>
          <label for="link">Link</label>
        </div>
        <div class="input-field">
          <%= text_input f, :image, [id: "image", required: true] %>
          <label for="image">Image</label>
        </div>
        <div class="input-field">
          <%= text_input f, :price, [id: "price", required: true] %>
          <label for="price">Price</label>
        </div>
        <%= hidden_input f, :tags, [value: ""] %>
        <%= hidden_input f, :list_id, [value: Listless.Util.convert_to_uuid(@list_id)] %>
        <%= submit "Add Item", [class: "btn white"] %>
      <% end %>
    </div>
  <% end %>
</article>